name: Go

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'
env:
  CGO_CFLAGS: -D__BLST_PORTABLE__
  CGO_CFLAGS_ALLOW: -D__BLST_PORTABLE__

jobs:

  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Lint
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          install-go: false
          version: "2021.1.1"

      - name: Test
        run: go test -v ./...

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make

      - name: Run coverage
        run:  go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          token:
          files: ./coverage.txt
          flags:  unittests
          name: venus-wallet
          fail_ci_if_error: true
          verbose: true
