name: Go

on:
  push:
    branches:
      - master
    paths-ignore: ["*.md", "docs/**"]
  pull_request:
    branches:
      - '**'
    paths-ignore: ["*.md", "docs/**"]
env:
  CGO_CFLAGS: -D__BLST_PORTABLE__
  CGO_CFLAGS_ALLOW: -D__BLST_PORTABLE__

jobs:

  check:
    uses: filecoin-project/venus/.github/workflows/common_go.yml@master
    with:
      has_ffi: false
